version: "3"

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    expose:
      - '8000'
    env_file:
      - .env.local
    volumes:
      - .:/usr/src/app
      - ./media:/usr/src/app/media
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    
    expose:
      - '5432'
    
    env_file:
      - .env.local
  
  redis:
    image: redis:6.0.1
    env_file:
      - .env.local
    ports:
      - 6379:6379
    depends_on:
      - web

volumes:
  postgres_data:
